In [4]:
from micecat_auto import *

In [5]:
request_id_dict = {}
for icat in np.arange(185,200,1):
    driver = query_micecat()
    sql = gen_sql(icat, select_top=None)
    request_id = sendSQL_micecat(driver, sql)
    request_id_dict[icat] = request_id
    print('query cat %d, request id %d'%(icat, request_id))
    driver.quit()
    
    time.sleep(120)
    driver = dowload_micecat({icat: request_id})
    time.sleep(60)
    driver.quit()
    process_downloaded_micecat({icat: request_id})

query cat 185, request id 7235
query cat 186, request id 7236
query cat 187, request id 7237
query cat 188, request id 7238
query cat 189, request id 7239
query cat 190, request id 7240
query cat 191, request id 7241
query cat 192, request id 7242
query cat 193, request id 7243
query cat 194, request id 7244
query cat 195, request id 7245
query cat 196, request id 7246
query cat 197, request id 7247
query cat 198, request id 7248
query cat 199, request id 7249


In [4]:
batch_size=20
ibatch=0
istart=0
icat_arr = np.linspace(0, batch_size-1, batch_size) + ibatch*batch_size + istart
icat_arr

In [3]:
from micecat_auto import *

df = get_micecat_df_auto(44)

In [15]:
def get_micecat_sim_cen(inst, im, sub=False, 
    filt_order=None, ratio=False, return_icat=False):
    '''
    Get the MICECAT central gal sim results.
    '''
    savedir='./micecat_data/all_fields/'
    typename = 'filter_test_cen'
    data_all = []
    icat_arr = []
    for icat in range(200):
        fname  = typename + '_TM%d_icat%d.pkl'%(inst, icat)
        if fname not in os.listdir(savedir):
            continue
        icat_arr.append(icat)
        
        with open(savedir + fname,"rb") as f:
            data_dict = pickle.load(f)
            
        if not sub:
            rbinedges = data_dict['rbinedges']
            rbins = data_dict['rbins']
            data = data_dict['data']
        else:
            rbinedges = data_dict['rsubbinedges']
            rbins = data_dict['rsubbins']
            data = data_dict['datasub']
            
        print(icat, data)
        data_all.append(data)
    
    filt_order_arr = np.array(data_dict['filt_order_arr'])
    icat_arr = np.array(icat_arr)
    data_all = np.array(data_all)[...,im,:]
    if ratio:
        for i in range(data_all.shape[0]):
            nofilt = data_all[i,0,:].copy()
            for j in range(data_all.shape[1]):
                data_all[i,j,:] = data_all[i,j,:]/nofilt
                
    data_avg = np.mean(data_all, axis=0)
    data_std = np.std(data_all, axis=0)
    
    if filt_order is None:
        if return_icat:
            return rbins, data_avg, data_std, data_all, filt_order_arr, icat_arr
        return rbins, data_avg, data_std, data_all, filt_order_arr
    
    else:
        sp = np.where(filt_order_arr==filt_order)[0]
        data_avg = np.squeeze(data_avg[sp])
        data_std = np.squeeze(data_std[sp])
        data_all = np.squeeze(data_all[:,sp,:])
        if return_icat:
            return rbins, data_avg, data_std, data_all, icat_arr
        return rbins, data_avg, data_std, data_all

In [16]:
get_micecat_sim_cen(1, 0, filt_order=0)

0 [[[ 0.          0.          0.          0.          0.
    0.          0.         -0.05155585  0.03524491  0.
    0.02774362 -0.02940941 -0.07742267  0.08392865  0.06417979
    0.0174868   0.00990387 -0.03039716 -0.02512841 -0.03348073
   -0.02782879 -0.00551524 -0.01211628  0.00260362 -0.00830385]
  [ 0.          0.          0.          0.          0.
    0.          0.          0.44267983 -0.04483894  0.
    0.12283318 -0.03382087 -0.01862502 -0.05401132  0.05771735
    0.01344146  0.0061801   0.01368063  0.00764717  0.00244771
    0.00688355  0.00115551 -0.00641383 -0.00825869 -0.0132308 ]
  [ 0.          0.          0.          0.          0.
    0.          0.          0.          0.          0.
    0.          0.          0.          0.          0.
    0.          0.          0.          0.          0.
    0.          0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.          0.
    0.          0.          0.          0.          0.
    

(array([7.00000000e-01, 9.89949494e-01, 1.51016506e+00, 2.12677193e+00,
        2.76499469e+00, 3.63016492e+00, 4.87088528e+00, 6.59340628e+00,
        8.92810227e+00, 1.20205026e+01, 1.61929298e+01, 2.18290205e+01,
        2.93587176e+01, 3.95236410e+01, 5.32378852e+01, 7.16704790e+01,
        9.65182360e+01, 1.29967986e+02, 1.74976207e+02, 2.35605901e+02,
        3.17238977e+02, 4.27140809e+02, 5.75121999e+02, 7.69048041e+02,
        9.78658735e+02]),
 array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        , -0.05155585,  0.03524491,  0.        ,
         0.02774362, -0.02940941, -0.07742267,  0.08392865,  0.06417979,
         0.0174868 ,  0.00990387, -0.03039716, -0.02512841, -0.03348073,
        -0.02782879, -0.00551524, -0.01211628,  0.00260362, -0.00830385]),
 array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.15105711e-16,
        6.24500451e-17, 0.00000

In [ ]:
run_micecat_auto_batch(1,0)